import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';

// ─── Mock DB ─────────────────────────────────────────────────────────────────
const waitData: any[] = [];
const mockDb = vi.hoisted(() => {
  function makeChainable() {
    const chain: any = () => chain;
    chain.select = vi.fn(() => chain);
    chain.from = vi.fn(() => chain);
    chain.where = vi.fn(() => chain);
    chain.limit = vi.fn(() => chain);
    chain.orderBy = vi.fn(() => chain);
    chain.insert = vi.fn(() => chain);
    chain.values = vi.fn(() => chain);
    chain.returning = vi.fn(() => chain);
    chain.update = vi.fn(() => chain);
    chain.set = vi.fn(() => chain);
    chain.delete = vi.fn(() => chain);
    chain.then = vi.fn((resolve: (value: any) => void) => {
      const data = waitData.shift();
      resolve(data !== undefined ? data : []);
    });
    chain.catch = vi.fn();
    return chain;
  }
  return makeChainable();
});

vi.mock('../db/index.js', () => ({ db: mockDb, runMigrations: vi.fn() }));

// ─── Mock auth ───────────────────────────────────────────────────────────────
vi.mock('../auth/index.js', () => ({
  authGuard: vi.fn((request: any, _reply: any, done: any) => {
    request.user = { userId: 'user-1', username: 'testuser' };
    done?.();
  }),
  signToken: vi.fn(() => 'mock-token'),
  verifyToken: vi.fn(() => ({ userId: 'user-1' })),
  hashPassword: vi.fn(),
  verifyPassword: vi.fn(),
}));

// ─── Mock socket (don't need real socket.io) ─────────────────────────────────
vi.mock('../socket/index.js', () => ({
  initSocket: vi.fn(() => ({})),
  getIO: vi.fn(() => ({
    to: vi.fn(() => ({ emit: vi.fn() })),
    emit: vi.fn(),
  })),
  getUserSocketIds: vi.fn(() => []),
}));

// ─── Mock notifications (avoid fire-and-forget DB queries leaking into the
//     waitData queue — the challenge route triggers one per send) ────────────
vi.mock('../services/notifications.js', () => ({
  createNotification: vi.fn(async () => ({
    id: 'n-1',
    read: false,
    createdAt: new Date().toISOString(),
  })),
}));

// ─── Mock email ──────────────────────────────────────────────────────────────
vi.mock('../lib/email.js', () => ({
  isEmailConfigured: vi.fn(() => false),
  sendPasswordResetEmail: vi.fn(),
}));

import { buildApp } from '../index.js';

function setupMockDb() {
  waitData.length = 0;
  mockDb.select.mockReturnThis();
  mockDb.from.mockReturnThis();
  mockDb.where.mockReturnThis();
  mockDb.limit.mockReturnThis();
  mockDb.orderBy.mockReturnThis();
  mockDb.insert.mockReturnThis();
  mockDb.values.mockReturnThis();
  mockDb.returning.mockReturnThis();
  mockDb.update.mockReturnThis();
  mockDb.set.mockReturnThis();
  mockDb.delete.mockReturnThis();
}

describe('buildApp', () => {
  beforeEach(() => {
    vi.clearAllMocks();
    setupMockDb();
  });

  it('should build app without throwing', async () => {
    const app = await buildApp();
    expect(app).toBeDefined();
    await app.close();
  });

  it('should set anti-cache headers on responses', async () => {
    const app = await buildApp();
    const res = await app.inject({
      method: 'GET',
      url: '/api/health',
    });
    expect(res.headers['cache-control']).toBe('no-store, no-cache, must-revalidate, proxy-revalidate, no-transform');
    expect(res.headers['pragma']).toBe('no-cache');
    expect(res.headers['expires']).toBe('0');
    await app.close();
  });

  it('should register all route modules', async () => {
    const app = await buildApp();

    // Health
    let res = await app.inject({ method: 'GET', url: '/api/health' });
    expect(res.statusCode).toBe(200);

    // Auth routes — register returns 400 when no body (route is registered)
    res = await app.inject({ method: 'POST', url: '/api/auth/register', payload: {} });
    expect(res.statusCode).not.toBe(404);

    await app.close();
  });
});

describe('POST /api/matches/challenge — pending challenge replacement', () => {
  const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

  it('should create a challenge when no pending challenge exists', async () => {
    // 1. friendship check
    waitData.push([{ userId: 'user-1', friendId: 'user-2', status: 'accepted' }]);
    // 2. no existing pending challenge
    waitData.push([]);
    // 3. createChallenge insert (id is generated by the service, value ignored)
    waitData.push(undefined);
    // 4. challenger user select (socket notification)
    waitData.push([{ id: 'user-1', username: 'testuser', displayName: null, avatarUrl: null, isVerified: false }]);

    const app = await buildApp();
    const res = await app.inject({
      method: 'POST',
      url: '/api/matches/challenge',
      payload: { receiverId: 'user-2', gameModeSlug: 'classic' },
    });

    expect(res.statusCode).toBe(200);
    expect(res.json().challengeId).toMatch(UUID_RE);
    await app.close();
  });

  it('should replace an existing pending challenge and return the new id', async () => {
    waitData.push([{ userId: 'user-1', friendId: 'user-2', status: 'accepted' }]);
    // existing pending challenge found
    waitData.push([{ id: 'ch-1', challengerId: 'user-1', receiverId: 'user-2', status: 'pending' }]);
    waitData.push(undefined); // delete old challenge
    waitData.push(undefined); // createChallenge insert
    waitData.push([{ id: 'user-1', username: 'testuser', displayName: null, avatarUrl: null, isVerified: false }]);

    const app = await buildApp();
    const res = await app.inject({
      method: 'POST',
      url: '/api/matches/challenge',
      payload: { receiverId: 'user-2', gameModeSlug: 'classic' },
    });

    expect(res.statusCode).toBe(200);
    expect(res.json().challengeId).toMatch(UUID_RE);
    expect(mockDb.delete).toHaveBeenCalled();
    await app.close();
  });

  it('should return 409 CHALLENGE_IN_FLIGHT if the old challenge is being accepted concurrently', async () => {
    waitData.push([{ userId: 'user-1', friendId: 'user-2', status: 'accepted' }]);
    waitData.push([{ id: 'ch-1', challengerId: 'user-1', receiverId: 'user-2', status: 'pending' }]);

    // The delete chain rejects with a Postgres FK violation (23503). Must call
    // the reject callback — a thenable's return value is ignored by await.
    const chain = vi.fn(() => chain) as any;
    chain.where = vi.fn(() => chain);
    chain.then = vi.fn((_resolve: any, reject: any) =>
      reject(Object.assign(new Error('FK violation'), { code: '23503' })),
    );
    chain.catch = vi.fn();
    mockDb.delete.mockReturnValueOnce(chain);

    const app = await buildApp();
    const res = await app.inject({
      method: 'POST',
      url: '/api/matches/challenge',
      payload: { receiverId: 'user-2', gameModeSlug: 'classic' },
    });

    expect(res.statusCode).toBe(409);
    expect(res.json().errorCode).toBe('CHALLENGE_IN_FLIGHT');
    await app.close();
  });

  it('should return 409 PENDING_CHALLENGE if a concurrent send wins the insert race', async () => {
    waitData.push([{ userId: 'user-1', friendId: 'user-2', status: 'accepted' }]);
    waitData.push([]); // no pending challenge found at select time

    // The insert chain rejects with a Postgres unique violation (23505)
    const chain = vi.fn(() => chain) as any;
    chain.values = vi.fn(() => chain);
    chain.then = vi.fn((_resolve: any, reject: any) =>
      reject(Object.assign(new Error('unique violation'), { code: '23505' })),
    );
    chain.catch = vi.fn();
    mockDb.insert.mockReturnValueOnce(chain);

    const app = await buildApp();
    const res = await app.inject({
      method: 'POST',
      url: '/api/matches/challenge',
      payload: { receiverId: 'user-2', gameModeSlug: 'classic' },
    });

    expect(res.statusCode).toBe(409);
    expect(res.json().errorCode).toBe('PENDING_CHALLENGE');
    await app.close();
  });
});
