export { healthRoutes } from './health.js';
export { authRoutes } from './auth.js';
export { quizRoutes } from './quiz.js';
export { countriesRoutes } from './countries.js';
export { friendsRoutes } from './friends.js';
export { chatRoutes } from './chat.js';
export { rankingsRoutes } from './rankings.js';
export { profileRoutes } from './profile.js';
export { notificationsRoutes } from './notifications.js';
